"""about field i whisky

Revision ID: 68b486e77186
Revises: e3d3628e052d
Create Date: 2018-02-04 15:36:17.646913

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68b486e77186'
down_revision = 'e3d3628e052d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('whisky', sa.Column('about', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('whisky', 'about')
    # ### end Alembic commands ###
