"""distillery info

Revision ID: d24cf9590e9d
Revises: 9bc08813b000
Create Date: 2019-04-22 13:58:46.692715

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd24cf9590e9d'
down_revision = '9bc08813b000'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('distillery', sa.Column('founded', sa.Integer(), nullable=True))
    op.add_column('distillery', sa.Column('owner', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('distillery', 'owner')
    op.drop_column('distillery', 'founded')
    # ### end Alembic commands ###
