"""added whiskies_listed

Revision ID: d606df1b7e4a
Revises: d24cf9590e9d
Create Date: 2019-04-23 23:14:46.470195

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd606df1b7e4a'
down_revision = 'd24cf9590e9d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('whiskies_listed',
    sa.Column('whisky_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['whisky_id'], ['whisky.id'], ),
    sa.PrimaryKeyConstraint('whisky_id', 'user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('whiskies_listed')
    # ### end Alembic commands ###
